# Generated by Django 4.2.3 on 2023-09-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0002_post_genres"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["genres"], name="Blog_post_genres_db7cb9_idx"),
        ),
    ]
