# Generated by Django 4.2.3 on 2023-09-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0003_post_blog_post_genres_db7cb9_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=50),
        ),
    ]
